version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: demo-yez-vn
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./index.html:/var/www/demo.yez.vn/index.html:ro
      - ./nginx.conf:/etc/nginx/conf.d/demo.yez.vn.conf:ro
      - ./ssl:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot-demo-yez
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./webroot:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email admin@yez.vn --agree-tos --no-eff-email -d demo.yez.vn
    depends_on:
      - nginx
    networks:
      - web

networks:
  web:
    driver: bridge 